### PR TITLE
Added parsing for int and int32

### PR DESCRIPTION
**Pull request by rbo13**
- Supports parsing for int.

ref: #6

### CODE REVIEW

**Comment by mufti1** [comment]
can you make the test code to 100% coverage?

**Comment by rbo13** [comment]
Sure @mufti1 👍 will update my PR :)

**Comment by mufti1** [comment]
great don't forget place your name into contribute.md

**Comment by rbo13** [comment]
Okay 👍 will add it. Will just add the conversion of `int32` in a bit :)

**Comment by mufti1** [comment]
> Okay  will add it. Will just add the conversion of `int32` in a bit :)

okay i'll wait it

**Comment by rbo13** [comment]
Hi @mufti1 👍 I've already added myself as one of the contributors. You can also check my PR if its correct :)

**Comment by mufti1** [comment]
> Hi @mufti1  I've already added myself as one of the contributors. You can also check my PR if its correct :)

okay i'll check

**Comment by mufti1** [comment]
merged :+1:

**Comment by rbo13** [comment]
Thanks @mufti1 👍

**Pull request merged**
